### ISSUE TITLE
Adding groupBy operator. 

### ISSUE THREAD

**Issue by yegorsch** [google/functional-objc#4]
Hi! I am considering adding groupBy method to the list. I think it would be pretty useful.

**Comment by shoumikhin** [comment]
Sounds good, Yegor!

Could you please provide some use cases for such methods for different container types that we support (NSArray, NSSet, NSOrderedSet, NSDictionary)? May also like to implement them as test cases.

Thanks.

**Comment by yegorsch** [comment]
Here are some simple use cases.

``` objc
- (void)testGroupByArray {
  // Arrange.
  NSArray<NSNumber *> *originalArray = @[ @5, @6, @7 ];
  NSDictionary<NSString *, NSArray<NSNumber *> *> *expectedDict = @{@"even" : @[ @6 ], @"odd": @[ @5,  @7 ]};

  // Act.
  NSDictionary<NSString *, NSArray<NSNumber *> *> *resultingDict= [originalArray fbl_groupby:^id(NSNumber *value) {
    if (value.integerValue % 2) {
      return @"odd";
    }
    return @"even";
  }];

  // Assert.
  XCTAssertEqualObjects(resultingDict, expectedDict);
}

- (void)testGroupByValueDictionary {
  // Arrange.
  NSDictionary<NSString *, NSNumber *> *originalDictionary = @{ @"one" : @12, @"two" : @40, @"three" : @13 };
  NSDictionary<NSString *, NSDictionary<NSString *, NSNumber *> *>
      *expectedDict = @{
        @"evenValues" : @{@"one" : @12, @"two" : @40},
        @"oddValues" : @{@"three" : @13}
      };

  // Act.
  NSDictionary<NSString *, NSDictionary<NSString *, NSNumber *> *>
      *resultingDict = [originalDictionary
          fbl_groupby:^NSString *(NSString *key, NSNumber *value) {
            if (value.integerValue % 2) {
              return @"oddValues";
            }
            return @"evenValues";
          }];

  // Assert.
  XCTAssertEqualObjects(resultingDict, expectedDict);
}

- (void)testGroupByOrderedSet {
  // Arrange.
  NSOrderedSet<NSNumber *> *originalOrderedSet =
      [NSOrderedSet orderedSetWithArray:@[ @13, @42, @0 ]];
  NSDictionary<NSString *, NSArray<NSNumber *> *> *expectedDict =
      @{ @"even" : @[ @42, @0 ],
         @"odd" : @[ @13 ] };

  // Act.
  NSDictionary<NSString *, NSArray<NSNumber *> *> *resultingDict = [originalOrderedSet fbl_groupby:^id(NSNumber *value) {
    if (value.integerValue % 2) {
      return @"odd";
    }
    return @"even";
  }];

  // Assert.
  XCTAssertEqualObjects(resultingDict, expectedDict);
}

- (void)testGroupBySet {
  // Arrange.
  NSSet<NSNumber *> *originalOrderedSet =
  [NSSet setWithArray:@[@13, @42, @0]];
  NSDictionary<NSString *, NSArray<NSNumber *> *> *expectedDict =
  @{ @"even" : @[ @42, @0 ],
     @"odd" : @[ @13 ] };

  // Act.
  NSDictionary<NSString *, NSArray<NSNumber *> *> *resultingDict = [originalOrderedSet fbl_groupby:^id(NSNumber *value) {
    if (value.integerValue % 2) {
      return @"odd";
    }
    return @"even";
  }];

  // Assert.
  XCTAssertEqualObjects(resultingDict, expectedDict);
}


```

**Comment by ghost** [comment]
Hey Yegor, 

Thank you for the sample unit tests! 

Can you provide some use cases demonstrating when fbl_groupBy would be helpful in production code?

**Comment by yegorsch** [comment]
Well, I have an example off the top of my head. Supposedly, we have an array of news models where each news instance has name, description, publisher and date. fbl_groupBy publisher, for example, would give us a dictionary of array of news with a corresponding publisher as a key. Keys can be further used to populate some sort of NewsFilterView where we can select publishers we are interested in.  
Something like that: 
``` objc 
  NSDictionary<NSString *, NSArray<News *> *> *newsByPublisherDictionary= [newsArray   NSDictionary<NSString *, NSArray<News *> *> *newsByPublisherDictionary =
      [newsArray fbl_groupBy:^NSString *(News *instance) {
        return instance.publisherName;
      }];
```

**Comment by shoumikhin** [comment]
Thank you for the examples, Yegor!

It seems like you're referring something like Dictionary's [`init(grouping:by:)`](https://developer.apple.com/documentation/swift/dictionary/2919592-init) constructor in Swift?
I believe if we wanted something similar in Objective-C, it should be implemented the same way, as:

`+ (instancetype)dictionaryWithObjects:(NSArray<ObjectType> *)objects groupedBy:(id<NSCopying>(^)(ObjectType *))keyForValue`

And this library provides just a subset of most popular functional primitives that follow[`Sequence`](https://developer.apple.com/documentation/swift/sequence) methods, not a bunch of convenience initializers for `NSDictionary`, etc.

**Comment by yegorsch** [comment]
Oh I see. Did not know about that one.
