### ISSUE TITLE
Can't setup by Swift Packages

### ISSUE THREAD

**Issue by sglushchenko** [google/functional-objc#9]
When I try setup this library to my project by Swift Packages Manager I have error

`package 'FBLFunctional' contains no products`

I think you should add `products` field to Package.swift file

similar with AFNetworking

`https://github.com/AFNetworking/AFNetworking/blob/master/Package.swift`

Thank you

**Comment by shoumikhin** [comment]
Hi @sglushchenko,

Please send a PR our way, happy to merge in a fix!

Thanks.
